#!/usr/bin/env bash
set -Eeuo pipefail

CONFIG_FILE="${1:-sushi-config.yaml}"
PACKAGE_FILE="package.json"

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

for command in fhir yq jq; do
  command -v "$command" >/dev/null 2>&1 \
    || fail "Required command '$command' was not found in PATH."
done

[[ -f "$CONFIG_FILE" ]] \
  || fail "Could not find '$CONFIG_FILE' in the current directory."

# This script expects Mike Farah yq v4: https://github.com/mikefarah/yq
if ! yq --version 2>&1 | grep -qi 'mikefarah'; then
  fail "This script requires Mike Farah yq v4."
fi

package_id="$(yq -r '.id // ""' "$CONFIG_FILE")"
package_version="$(yq -r '.version // ""' "$CONFIG_FILE")"
description="$(yq -r '.description // ""' "$CONFIG_FILE")"
fhir_version="$(yq -r '.fhirVersion // ""' "$CONFIG_FILE")"
sushi_dependencies="$(yq -o=json -I=0 '.dependencies // {}' "$CONFIG_FILE")"

[[ -n "$package_id" ]]      || fail "Missing required 'id' in $CONFIG_FILE."
[[ -n "$package_version" ]] || fail "Missing required 'version' in $CONFIG_FILE."
[[ -n "$fhir_version" ]]    || fail "Missing required 'fhirVersion' in $CONFIG_FILE."

jq -e 'type == "object"' <<<"$sushi_dependencies" >/dev/null \
  || fail "'dependencies' in $CONFIG_FILE must be a YAML mapping."

# Firely Terminal selects the FHIR release by name rather than the full version.
case "$fhir_version" in
  3.0.*) firely_spec="stu3" ;;
  4.0.*) firely_spec="r4" ;;
  4.3.*) firely_spec="r4b" ;;
  5.0.*) firely_spec="r5" ;;
  *)
    fail "Unsupported fhirVersion '$fhir_version'. Add its Firely spec mapping to the case statement."
    ;;
esac

# Temporarily preserve an existing package.json and restore it if anything fails.
previous_package=""
output_tmp=""
succeeded=false

cleanup() {
  status=$?

  [[ -z "$output_tmp" ]] || rm -f "$output_tmp"

  if [[ "$succeeded" != true && -n "$previous_package" && -f "$previous_package" ]]; then
    rm -f "$PACKAGE_FILE"
    mv "$previous_package" "$PACKAGE_FILE"
    printf 'Restored the previous %s because initialization failed.\n' "$PACKAGE_FILE" >&2
  elif [[ -n "$previous_package" ]]; then
    rm -f "$previous_package"
  fi

  exit "$status"
}
trap cleanup EXIT

if [[ -f "$PACKAGE_FILE" ]]; then
  previous_package="$(mktemp)"
  cp -p "$PACKAGE_FILE" "$previous_package"
  rm "$PACKAGE_FILE"
fi

printf 'Selecting Firely specification: %s\n' "$firely_spec"
fhir spec "$firely_spec"

printf 'Initializing Firely package: %s@%s\n' "$package_id" "$package_version"
fhir init "$package_id" "$package_version"

[[ -f "$PACKAGE_FILE" ]] \
  || fail "fhir init completed without creating $PACKAGE_FILE."

# Keep dependencies generated by Firely, especially the correct FHIR core package,
# and merge the dependencies declared by SUSHI over them.
firely_dependencies="$(jq -c '.dependencies // {}' "$PACKAGE_FILE")"

output_tmp="$(mktemp "${PACKAGE_FILE}.tmp.XXXXXX")"

jq -n \
  --arg name "$package_id" \
  --arg version "$package_version" \
  --arg description "$description" \
  --arg fhir_version "$fhir_version" \
  --argjson firely_dependencies "$firely_dependencies" \
  --argjson sushi_dependencies "$sushi_dependencies" \
  '{
    name: $name,
    version: $version,
    description: $description,
    dependencies: ($firely_dependencies + $sushi_dependencies),
    fhirVersions: [$fhir_version]
  }' > "$output_tmp"

mv "$output_tmp" "$PACKAGE_FILE"
output_tmp=""
succeeded=true

printf 'Created %s from %s.\n' "$PACKAGE_FILE" "$CONFIG_FILE"
printf 'Restoring Firely packages...\n'
if fhir restore; then
  printf 'Firely package restore completed.\n'
else
  restore_status=$?
  printf 'Warning: Firely package restore exited with status %d;\n' \
    "$restore_status" >&2
fi