name: Update Publisher

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  update-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get latest HL7 release
        run: |
          LATEST_RELEASE=$(
            curl -sL \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/repos/HL7/fhir-ig-publisher/releases/latest \
              | jq -r .tag_name
          )

          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Print latest release
        run: |
          echo "Latest release: $LATEST_RELEASE"

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            IG_PUB_VERSION=${{ env.LATEST_RELEASE }}
          tags: ghcr.io/medcomdk/medcom-github-actions-container:${{ env.LATEST_RELEASE }}-with-firely-terminal
          
