name: Update Publisher

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  update-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get latest HL7 release
        run: |
          LATEST_RELEASE=$(
            curl -sL \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/repos/HL7/fhir-ig-publisher/releases/latest \
              | jq -r .tag_name
          )

          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Print latest release
        run: |
          echo "Latest release: $LATEST_RELEASE"

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Get current container version
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep "container:" .github/workflows/qa-report.yaml | sed -E 's|.*:([0-9]+\.[0-9]+\.[0-9]+)-with-firely-terminal|\1|')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Compare versions
        id: compare_versions
        run: |
          echo "Latest:  $LATEST_RELEASE"
          echo "Current: $CURRENT_VERSION"

          if [ "$LATEST_RELEASE" = "$CURRENT_VERSION" ]; then
            echo "SKIP_UPDATE=true" >> $GITHUB_ENV
            echo "Versions are identical. Skipping update."
          else
            echo "SKIP_UPDATE=false" >> $GITHUB_ENV
            echo "New version found. Continuing."
          fi

      
      - name: Build & push Docker image
        if: env.SKIP_UPDATE != 'true'
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            IG_PUB_VERSION=${{ env.LATEST_RELEASE }}
          tags: ghcr.io/medcomdk/medcom-github-actions-container:${{ env.LATEST_RELEASE }}-with-firely-terminal
          
      - name: Update qa-report.yaml with latest publisher version
        if: env.SKIP_UPDATE != 'true'
        run: |
          echo "Updating qa-report.yaml with latest publisher version: ${LATEST_RELEASE}-with-firely-terminal"
          sed -i -E \
            "s|(container:[[:space:]]+[^[:space:]]+):[^[:space:]]+|\1:${LATEST_RELEASE}-with-firely-terminal|" \
            ./.github/workflows/qa-report.yaml

      - name: Verify qa-report.yaml
        if: env.SKIP_UPDATE != 'true'
        run: |
          grep "container:" ./.github/workflows/qa-report.yaml

         
      - name: Updating publish.yaml with latest publisher version
        if: env.SKIP_UPDATE != 'true'
        run: |
          echo "Updating publish.yaml with latest publisher version: ${LATEST_RELEASE}-with-firely-terminal"
          sed -i -E \
            "s|(container:[[:space:]]+[^[:space:]]+):[^[:space:]]+|\1:${LATEST_RELEASE}-with-firely-terminal|" \
            ./.github/workflows/publish.yaml

      - name: Verify publish.yaml
        if: env.SKIP_UPDATE != 'true'
        run: |
          grep "container:" ./.github/workflows/publish.yaml
          