name: Update Publisher

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-publisher:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest HL7 release
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/HL7/fhir-ig-publisher/releases/latest